addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
sudo: false
script:
- make final
deploy:
  provider: releases
  api_key:
    secure: ELDaM7tobWkh9w4Be04RdOSK1vSSTT4uGhBFIMxjhz5BWalkRCxgQsmfsmnYc7qPVudlkRsTJpEAK7B9zlEBKvZrCx8ICouSy+KNZgZiZ25itAzZr+4bnSspW15IuwN5FHe8F8gLoCtKTNFKPWHSGf1aV86nQ/6XuE4NznudB8CtEc6OitC4xiIYjNeQnG2VLcCgJEmRN1MEf9OGpN3PRXIghfsfS0td3qQd0BD+Qpktm5hrtDpMKCocXBz5uWhU5xtIFbEsxYVmrmG1apqEVXf4nom5PaedvhvSotuQA0+Lt8Isc0oaHNWrppliWX7SgnoNyfckHGVB93n8sBlOBp70i1G6ZZAYH9slc5tBMZn15i7TDepH7Cdd1mkJWKbvqmMOZnnAP8pDoAKCJqQiRtMPYp9Bp8hm7+Emk/eXu5V6PBhtBITJGfvz72sTihpwh+ZCBK08klQIq5kpV8Z8zpqyDXoNxymdO0jqCdKMUt6cOMBz1rLPQcu78dAqRr7KUg//Eq55Emqn6H1iGOxFQTuqfEA+4WX7ig7U6/mlmEl6UK2zxXpr04r1iXmP5q0HZZvibDStksfijsvF3jmPFqEd89zuVap2rEiSpw03M1uRiKhaIUHGNiwitbvohOaWfI5jXLb37/c/iwNL5FjYXUcQ35XZEBQaUofntaH2vss=
  file: resume.pdf
  skip_cleanup: true
  on:
    repo: pittenga/resume
    tags: true
